name: Pull Request
description: File a Pull Request
title: "PR: "
labels: ["pull-request", "pr"]
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      placeholder: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps-reproduce
    attributes:
      label: Steps to reproduce
      description: Describe Steps to reproduce the behavior
      placeholder: 1. Go to '...'
    validations:
      required: true
